---
title: "Notes: Singular Value Decomposition in Regression Analysis"
author: "Ivan Jacob Agaloos Pesigan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Notes: Singular Value Decomposition in Regression Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, packages, echo = FALSE, message = FALSE, warning = FALSE}
library(jeksterslabRdatarepo)
library(knitr)
library(DT)
library(GGally)
library(plotly)
library(psych)
```

## Load Data

```{r, load}
data(
  svd.linreg,
  package = "jeksterslabRdatarepo"
)
```

### Data A

```{r}
dataa <- as.data.frame(
  cbind(
    y = svd.linreg$ya,
    svd.linreg$Xa
  )
)
```

### Data B

```{r}
datab <- as.data.frame(
  cbind(
    y = svd.linreg$yb,
    svd.linreg$Xb
  )
)
```

## Data Table

### Data A

```{r, DT1, echo = FALSE}
datatable(
  data = dataa,
  options = list(
    pageLength = 8,
    dom = "t"
  )
)
```

### Data B

```{r, DT2, echo = FALSE}
datatable(
  data = datab,
  options = list(
    pageLength = 8,
    dom = "t"
  )
)
```

## Plots

### Scatter Plot Matrix

#### Data A

```{r, plot01, echo = FALSE, message = FALSE, warning = FALSE}
p <- ggpairs(
  data = dataa
)
ggplotly(p)
```

#### Data B

```{r, plot02, echo = FALSE, message = FALSE, warning = FALSE}
p <- ggpairs(
  data = datab
)
ggplotly(p)
```

## Descritive Statistics

### Data A

```{r, descriptives01, echo = FALSE}
kable(
  x = summary(
    dataa
  )
)
```

```{r, descriptives02, echo = FALSE, message = FALSE, warning = FALSE}
kable(
  x = describe(
    dataa
  )
)
```

### Data B

```{r, descriptives03, echo = FALSE}
kable(
  x = summary(
    datab
  )
)
```

```{r, descriptives04, echo = FALSE, message = FALSE, warning = FALSE}
kable(
  x = describe(
    datab
  )
)
```
